######################################################################
# Automatically generated by qmake (2.01a) Tue Sep 4 22:56:47 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += label.h mainwindow.h
FORMS += mainwindow.ui
SOURCES += label.cpp main.cpp mainwindow.cpp
